export const EVENT_API = "https://elixir-backendv2.vercel.app/events/?format=json";
export const NotesData = [
  {
    id: "0",
    title: "1st Year",
    text: "Even though it's 11th and 12th all over again, we've got you covered with first-year essentials+ C (iykyk)",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: "/sticky-notes.png",
    imageUrl: "/1.png",
    url: "https://drive.google.com/drive/folders/1TTjSSShjK5nrUURnSIVOK1wnO-CBCp7R",
  },
  {
    id: "1",
    title: "2nd Year",
    text: "Familiar with your UNI by now? Here is your cheat-sheet mate as the game's about to get real.",
    backgroundUrl: "./src/assets/benefits/card-2.svg",
    iconUrl: "/sticky-notes.png",
    imageUrl: "/2.png",
    light: true,
    url: "https://drive.google.com/drive/folders/1c2gZ8TJ53P3ecNETMB403lTueQY5pEHU",
  },
  {
    id: "2",
    title: "3rd Year",
    text: "Your tech-stack matters more than your Notes dump but we know backlogs suck. So you know the rules!",
    backgroundUrl: "./src/assets/benefits/card-3.svg",
    iconUrl: "/sticky-notes.png",
    imageUrl: "/3.png",
    url: "https://drive.google.com/drive/folders/1jUHgBPZdN5V5Am6gEHpHNTc4XWIQgC_W",
  },
  {
    id: "3",
    title: "4th Year",
    text: "Study some between your coffee breaks at office. Your handouts for an even shorter preparation. All the best for future big bird!",
    backgroundUrl: "./src/assets/benefits/card-4.svg",
    iconUrl: "/sticky-notes.png",
    imageUrl: "/4.png",
    light: true,
    url: "https://drive.google.com/drive/folders/1LdrCdkcasmu_qA0vOK-UdI8UeThNhZ2C",
  },
];
export const MentorData = [
  {
    name: "Anvesh",
    image: "/mentors/anvesh.png",
    discord: "_nimbu",
    linkedIn: "https://www.linkedin.com/in/anv3sh",
    techStack: "Django, Python, FastAPI, Flask, Data Structures, Back-end, SQL",
    bannerKeywords: "Backend",
  },
  {
    name: "Arjun",
    image: "/mentors/arjun.png",
    discord: "ar_ray0111",
    linkedIn: "https://www.linkedin.com/in/array0111",
    techStack: "Python, Django, FastAPI, PostgreSQL",
    bannerKeywords: "Backend",
  },
  {
    name: "Darshika",
    image: "/mentors/darshika.png",
    discord: "darshikaaa",
    linkedIn: "https://www.linkedin.com/in/darshika-gupta-7080a7217",
    techStack: "Frontend, Bootstrap, React.js, Web Development, JavaScript",
    bannerKeywords: "Frontend",
  },
  {
    name: "Manav Agarwal",
    image: "/mentors/manav.png",
    discord: "m4n4v014",
    linkedIn: "https://www.linkedin.com/in/manav014",
    techStack: "DevOps, Django, Open Source, Python",
    bannerKeywords: "Backend, DevOps",
  },
  {
    name: "Pulkit",
    image: "/mentors/pulkit.png",
    discord: "i__pulkit",
    linkedIn: "https://www.linkedin.com/in/pulkit30",
    techStack: "Full Stack, Open Source",
    bannerKeywords: "Fullstack, Opensource",
  },
  {
    name: "Sarthak Negi",
    image: "/mentors/sarthak.png",
    discord: "snegicodes",
    linkedIn: "https://www.linkedin.com/in/snegicodes",
    techStack: "JavaScript, Frontend Development",
    bannerKeywords: "Frontend",
  },
  {
    name: "Dewank Rastogi",
    image: "/mentors/dewank.png",
    discord: "deww07",
    linkedIn: "https://www.linkedin.com/in/dewankrastogi",
    techStack: "JavaScript, Frontend Development",
    bannerKeywords: "Frontend",
  },
  {
    name: "Shlok",
    image: "/mentors/shlok.png",
    discord: "jougan_",
    linkedIn: "https://www.linkedin.com/in/shlok08",
    techStack: "Golang, Deep learning",
    bannerKeywords: "Opensource, Frontend",
  },
  {
    name: "Tanveer Raza",
    image: "/mentors/tanveer.jpg",
    discord: "atamakahere",
    linkedIn: "https://www.linkedin.com/in/atamakahere",
    techStack: "Rust, Linux System Programming",
    bannerKeywords: "System programming",
  },
  {
    name: "Ishan Jindal",
    image: "/mentors/ishanj.png",
    discord: "ishanjindalece5",
    linkedIn: "https://www.linkedin.com/in/ishan-jindal-821950267/",
    techStack: "Verilog, Frontend Development",
    bannerKeywords: "Verilog Frontend Development",
  },
  {
    name: "Ram Goel",
    image: "/mentors/ram.png",
    discord: "none",
    linkedIn: "https://www.linkedin.com/in/ramgoel/",
    techStack: "Full Stack, GenAI",
    bannerKeywords: "Fullstack, GenAI",
  },
  {
    name: "Yash Grover",
    image: "/mentors/yash.png",
    discord: "chai0274",
    linkedIn: "https://www.linkedin.com/in/notyashgrover/",
    techStack: "UX, Mobile App Development, Front End Web Development",
    bannerKeywords: "Frontend, App development",
  },
  {
    name: "Abhinav Yadav",
    image: "/mentors/abhinavY.png",
    discord: "abhi0001",
    linkedIn: "https://www.linkedin.com/in/abhinavyadav13/",
    techStack: "Open Source",
    bannerKeywords: "Backend, Opensource",
  },
  // {
  //   name: "Bhumika Arora",
  //   image: "/mentors/bhumika.png",
  //   discord: "bhumika_arora",
  //   linkedIn: "https://www.linkedin.com/in/bhumikaarora2002/",
  //   techStack: "Application Developer",
  //   bannerKeywords: "App Dev",
  // },
  {
    name: "Vandit Singh",
    image: "/mentors/vandit.png",
    discord: "vandit1604",
    linkedIn: "https://www.linkedin.com/in/vandit-singh/",
    techStack: "DevOps, Open Source, Back-end, Golang",
    bannerKeywords: "Open Source, DevOps, Backend",
  },
  {
    name: "Keshav Jha",
    image: "/mentors/keshav.png",
    discord: ".keshavjha",
    linkedIn: "https://www.linkedin.com/in/keshav-jha-330776215/",
    techStack: "DSA Enthusiast, C++, Frontend, ReactJs",
    bannerKeywords: "Frontend, DSA",
  },
  {
    name: "Aparimit Rathour",
    image: "/mentors/aparimit.png",
    discord: "avgbrownguy",
    linkedIn: "https://www.linkedin.com/in/aparimit-rathour-533552243/",
    techStack: "Android Dev, Kotlin",
    bannerKeywords: "App Dev",
  },
  {
    name: "Rudraksh Tyagi",
    image: "/mentors/rudraksh.png",
    discord: "dragonslayer875",
    linkedIn: "https://www.linkedin.com/in/rudrakshtyagi875/",
    techStack: "Front End, Open Source",
    bannerKeywords: "Frontend, Open Source",
  },
  {
    name: "Shubhankar Gupta",
    image: "/mentors/shubhankar.png",
    discord: "shubhankargupta",
    linkedIn: "https://www.linkedin.com/in/shubhankar-gupta-aa8696235/",
    techStack: "Penetration Tester, Red Teamer, CTF Player, Golang, Java, Python, Linux, Git",
    bannerKeywords: "Cybersecurity",
  },
  {
    name: "Tejjus Bhatt",
    image: "/mentors/tejjus.png",
    discord: "ossicorsan",
    linkedIn: "https://www.linkedin.com/in/tejjusbhat/",
    techStack: "MERN, Flask, Pytorch, Tensor Flow, GenAI, Computer Vision",
    bannerKeywords: "ML, Frontend, AI",
  },
  {
    name: "Ishan Grover",
    image: "/mentors/ishan.png",
    discord: "ishangrover",
    linkedIn: "https://www.linkedin.com/in/ishangrover2004/",
    techStack: "Rust, C/C++, Linux",
    bannerKeywords: "System programming",
  },
  {
    name: "kartikey",
    image: "/mentors/kartikey.png",
    discord: "",
    linkedIn: "https://www.linkedin.com/in/kartikeya-mishra-52b722173/",
    techStack: "Cyber security, Networking, DevOps, Gen AI, Cloud Computing",
    bannerKeywords: "Cybersecurity",
  },
];
