export const EVENT_API = "https://elixir-backendv2.vercel.app/events/?format=json";
export const NotesData = [
  {
    id: "0",
    title: "1st Year",
    text: "Even though it's 11th and 12th all over again, we've got you covered with first-year essentials+ C (iykyk)",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: "/sticky-notes.png",
    imageUrl: "/1.png",
    url: "https://drive.google.com/drive/folders/1TTjSSShjK5nrUURnSIVOK1wnO-CBCp7R",
  },
  {
    id: "1",
    title: "2nd Year",
    text: "Familiar with your UNI by now? Here is your cheat-sheet mate as the game's about to get real.",
    backgroundUrl: "./src/assets/benefits/card-2.svg",
    iconUrl: "/sticky-notes.png",
    imageUrl: "/2.png",
    light: true,
    url: "https://drive.google.com/drive/folders/1c2gZ8TJ53P3ecNETMB403lTueQY5pEHU",
  },
  {
    id: "2",
    title: "3rd Year",
    text: "Your tech-stack matters more than your Notes dump but we know backlogs suck. So you know the rules!",
    backgroundUrl: "./src/assets/benefits/card-3.svg",
    iconUrl: "/sticky-notes.png",
    imageUrl: "/3.png",
    url: "https://drive.google.com/drive/folders/1jUHgBPZdN5V5Am6gEHpHNTc4XWIQgC_W",
  },
  {
    id: "3",
    title: "4th Year",
    text: "Study some between your coffee breaks at office. Your handouts for an even shorter preparation. All the best for future big bird!",
    backgroundUrl: "./src/assets/benefits/card-4.svg",
    iconUrl: "/sticky-notes.png",
    imageUrl: "/4.png",
    light: true,
    url: "https://drive.google.com/drive/folders/1LdrCdkcasmu_qA0vOK-UdI8UeThNhZ2C",
  },
];
export const MentorData = [
  {
    name: "Dewank Rastogi",
    description: "Currently working at amber Student, Talk to me about Frontend!",
    image: "/mentors/dewank.jpeg",
    skills: "React, Frontend",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Manav Agarwal",
    description: "Currently working at RechPlace, Talk to me about Django, Devops, System Design!",
    image: "/mentors/dewank.jpeg",
    skills: "Django, Devops, System Design, Go",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "John Doe",
    description: "Experienced React developer with a passion for building scalable web applications.",
    image: "/mentors/dewank.jpeg",
    skills: "React, Redux, TypeScript",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Jane Smith",
    description: "Full-stack developer proficient in Node.js, Express, and MongoDB.",
    image: "/mentors/dewank.jpeg",
    skills: "Node.js, Express, MongoDB",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Michael Johnson",
    description: "Skilled in Angular and front-end development with a focus on performance optimization.",
    image: "/mentors/dewank.jpeg",
    skills: "Angular, RxJS, Optimization",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Emily Davis",
    description: "Passionate about Python and data analysis, with experience in machine learning.",
    image: "/mentors/dewank.jpeg",
    skills: "Python, Data Analysis, Machine Learning",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "David Wilson",
    description: "Experienced in developing secure and scalable backend systems using Java and Spring.",
    image: "/mentors/dewank.jpeg",
    skills: "Java, Spring, Security",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Sophia Thompson",
    description: "Front-end developer with expertise in React Native and cross-platform mobile app development.",
    image: "/mentors/dewank.jpeg",
    skills: "React Native, Mobile Development",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "William Anderson",
    description: "Skilled in DevOps practices, containerization, and cloud deployment with Docker and Kubernetes.",
    image: "/mentors/dewank.jpeg",
    skills: "Docker, Kubernetes, DevOps",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Olivia Martinez",
    description: "Experienced in developing scalable and high-performance applications using Go.",
    image: "/mentors/dewank.jpeg",
    skills: "Go, Concurrency, Performance",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "James Brown",
    description: "Front-end developer with a strong focus on accessibility and inclusive design.",
    image: "/mentors/dewank.jpeg",
    skills: "Accessibility, Inclusive Design",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Ava Garcia",
    description: "Skilled in developing secure and robust applications using C# and .NET.",
    image: "/mentors/dewank.jpeg",
    skills: "C#, .NET, Security",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Benjamin Rodriguez",
    description: "Front-end developer with expertise in Vue.js and state management with Vuex.",
    image: "/mentors/dewank.jpeg",
    skills: "Vue.js, Vuex, State Management",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Isabella Hernandez",
    description: "Experienced in developing scalable and efficient back-end systems using Node.js and AWS.",
    image: "/mentors/dewank.jpeg",
    skills: "Node.js, AWS, Serverless",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Daniel Gonzalez",
    description: "Skilled in developing responsive and accessible web applications using React and Material-UI.",
    image: "/mentors/dewank.jpeg",
    skills: "React, Material-UI, Accessibility",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Sophia Perez",
    description: "Passionate about data visualization and front-end development with D3.js.",
    image: "/mentors/dewank.jpeg",
    skills: "D3.js, Data Visualization",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Alexander Sanchez",
    description: "Experienced in developing secure and scalable back-end systems using Ruby on Rails.",
    image: "/mentors/dewank.jpeg",
    skills: "Ruby on Rails, Security, Scalability",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Mia Torres",
    description: "Front-end developer with expertise in React and state management with Redux.",
    image: "/mentors/dewank.jpeg",
    skills: "React, Redux, State Management",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Matthew Rivera",
    description: "Skilled in developing scalable and efficient back-end systems using Python and Django.",
    image: "/mentors/dewank.jpeg",
    skills: "Python, Django, Scalability",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Abigail Ramirez",
    description: "Experienced in developing secure and robust applications using Java and Spring Boot.",
    image: "/mentors/dewank.jpeg",
    skills: "Java, Spring Boot, Security",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Jacob Flores",
    description: "Front-end developer with expertise in Angular and state management with NgRx.",
    image: "/mentors/dewank.jpeg",
    skills: "Angular, NgRx, State Management",
    discordLink: "#",
    LinkedinLink: "#",
  },
  {
    name: "Avery Gomez",
    description: "Skilled in developing scalable and efficient back-end systems using Node.js and MongoDB.",
    image: "/mentors/dewank.jpeg",
    skills: "Node.js, MongoDB, Scalability",
    discordLink: "#",
    LinkedinLink: "#",
  },
];
