export const randomProblemConst = {
  result: {
    dynamicArray: {
      id: "dynamicArray",
      name: "Design Dynamic Array (Resizable Array)",
      difficulty: "Easy",
      free: true,
      tag: "Implement Data Structures",
      unreleased: null,
    },
    singlyLinkedList: {
      id: "singlyLinkedList",
      name: "Design Singly Linked List",
      difficulty: "Easy",
      free: true,
      tag: "Implement Data Structures",
      unreleased: null,
    },
    queue: {
      id: "queue",
      name: "Design Double-ended Queue",
      difficulty: "Easy",
      free: false,
      tag: "Implement Data Structures",
      unreleased: null,
    },
    binarySearchTree: {
      id: "binarySearchTree",
      name: "Design Binary Search Tree",
      difficulty: "Medium",
      free: false,
      tag: "Implement Data Structures",
      unreleased: null,
    },
    hashTable: {
      id: "hashTable",
      name: "Design Hash Table",
      difficulty: "Medium",
      free: false,
      tag: "Implement Data Structures",
      unreleased: null,
    },
    heap: {
      id: "heap",
      name: "Design Heap",
      difficulty: "Medium",
      free: false,
      tag: "Implement Data Structures",
      unreleased: null,
    },
    graph: {
      id: "graph",
      name: "Design Graph",
      difficulty: "Medium",
      free: false,
      tag: "Implement Data Structures",
      unreleased: null,
    },
    unionFind: {
      id: "unionFind",
      name: "Design Disjoint Set (Union-Find)",
      difficulty: "Medium",
      free: false,
      tag: "Implement Data Structures",
      unreleased: null,
    },
    segmentTree: {
      id: "segmentTree",
      name: "Design Segment Tree",
      difficulty: "Hard",
      free: false,
      tag: "Implement Data Structures",
      unreleased: null,
    },
    insertionSort: {
      id: "insertionSort",
      name: "Insertion Sort",
      difficulty: "Easy",
      free: true,
      tag: "Sorting",
      unreleased: null,
    },
    mergeSort: {
      id: "mergeSort",
      name: "Merge Sort",
      difficulty: "Medium",
      free: false,
      tag: "Sorting",
      unreleased: null,
    },
    quickSort: {
      id: "quickSort",
      name: "Quick Sort",
      difficulty: "Medium",
      free: false,
      tag: "Sorting",
      unreleased: null,
    },
    matrixDFS: {
      id: "matrixDFS",
      name: "Matrix Depth-First Search",
      difficulty: "Medium",
      free: false,
      tag: "Graphs",
      unreleased: null,
    },
    matrixBFS: {
      id: "matrixBFS",
      name: "Matrix Breadth-First Search",
      difficulty: "Medium",
      free: false,
      tag: "Graphs",
      unreleased: null,
    },
    dijkstra: {
      id: "dijkstra",
      name: "Dijkstra's Algorithm",
      difficulty: "Medium",
      free: true,
      tag: "Graphs",
      unreleased: null,
    },
    prim: {
      id: "prim",
      name: "Prim's Algorithm",
      difficulty: "Hard",
      free: false,
      tag: "Graphs",
      unreleased: null,
    },
    kruskal: {
      id: "kruskal",
      name: "Kruskal's Algorithm",
      difficulty: "Hard",
      free: false,
      tag: "Graphs",
      unreleased: null,
    },
    topologicalSort: {
      id: "topologicalSort",
      name: "Topological Sort",
      difficulty: "Hard",
      free: false,
      tag: "Graphs",
      unreleased: null,
    },
    zeroOneKnapsack: {
      id: "zeroOneKnapsack",
      name: "0 / 1 Knapsack",
      difficulty: "Medium",
      free: false,
      tag: "Dynamic Programming",
      unreleased: null,
    },
    unboundedKnapsack: {
      id: "unboundedKnapsack",
      name: "Unbounded Knapsack",
      difficulty: "Medium",
      free: false,
      tag: "Dynamic Programming",
      unreleased: null,
    },
    factory: {
      id: "factory",
      name: "Factory Method Pattern",
      difficulty: "Easy",
      free: true,
      tag: "Design Patterns",
      unreleased: null,
    },
    singleton: {
      id: "singleton",
      name: "Singleton Pattern",
      difficulty: "Easy",
      free: false,
      tag: "Design Patterns",
      unreleased: null,
    },
    builder: {
      id: "builder",
      name: "Builder Pattern",
      difficulty: "Easy",
      free: false,
      tag: "Design Patterns",
      unreleased: null,
    },
    prototype: {
      id: "prototype",
      name: "Prototype Pattern",
      difficulty: "Easy",
      free: true,
      tag: "Design Patterns",
      unreleased: null,
    },
    adapter: {
      id: "adapter",
      name: "Adapter Pattern",
      difficulty: "Easy",
      free: true,
      tag: "Design Patterns",
      unreleased: null,
    },
    decorator: {
      id: "decorator",
      name: "Decorator Pattern",
      difficulty: "Easy",
      free: false,
      tag: "Design Patterns",
      unreleased: null,
    },
    facade: {
      id: "facade",
      name: "Facade Pattern",
      difficulty: "Easy",
      free: false,
      tag: "Design Patterns",
      unreleased: null,
    },
    strategy: {
      id: "strategy",
      name: "Strategy Pattern",
      difficulty: "Easy",
      free: false,
      tag: "Design Patterns",
      unreleased: null,
    },
    observer: {
      id: "observer",
      name: "Observer Pattern",
      difficulty: "Easy",
      free: false,
      tag: "Design Patterns",
      unreleased: null,
    },
    state: {
      id: "state",
      name: "State Pattern",
      difficulty: "Easy",
      free: null,
      tag: "Design Patterns",
      unreleased: null,
    },
    "duplicate-integer": {
      id: "duplicate-integer",
      name: "Duplicate Integer",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "string-encode-and-decode": {
      id: "string-encode-and-decode",
      name: "String Encode and Decode",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "count-connected-components": {
      id: "count-connected-components",
      name: "Count Connected Components",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "valid-tree": {
      id: "valid-tree",
      name: "Valid Tree",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "foreign-dictionary": {
      id: "foreign-dictionary",
      name: "Foreign Dictionary",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "meeting-schedule": {
      id: "meeting-schedule",
      name: "Meeting Schedule",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "meeting-schedule-ii": {
      id: "meeting-schedule-ii",
      name: "Meeting Schedule II",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "is-anagram": {
      id: "is-anagram",
      name: "Is Anagram",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "two-integer-sum": {
      id: "two-integer-sum",
      name: "Two Integer Sum",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "is-palindrome": {
      id: "is-palindrome",
      name: "Is Palindrome",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "islands-and-treasure": {
      id: "islands-and-treasure",
      name: "Islands and Treasure",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "buy-and-sell-crypto": {
      id: "buy-and-sell-crypto",
      name: "Buy and Sell Crypto",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "validate-parentheses": {
      id: "validate-parentheses",
      name: "Validate Parentheses",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "find-minimum-in-rotated-sorted-array": {
      id: "find-minimum-in-rotated-sorted-array",
      name: "Find Minimum in Rotated Sorted Array",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "reverse-a-linked-list": {
      id: "reverse-a-linked-list",
      name: "Reverse a Linked List",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "invert-a-binary-tree": {
      id: "invert-a-binary-tree",
      name: "Invert a Binary Tree",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "implement-prefix-tree": {
      id: "implement-prefix-tree",
      name: "Implement Prefix Tree",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "find-median-in-a-data-stream": {
      id: "find-median-in-a-data-stream",
      name: "Find Median in a Data Stream",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "combination-target-sum": {
      id: "combination-target-sum",
      name: "Combination Target Sum",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "count-number-of-islands": {
      id: "count-number-of-islands",
      name: "Count Number of Islands",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "climbing-stairs": {
      id: "climbing-stairs",
      name: "Climbing Stairs",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "count-paths": {
      id: "count-paths",
      name: "Count Paths",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "maximum-subarray": {
      id: "maximum-subarray",
      name: "Maximum Subarray",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "insert-new-interval": {
      id: "insert-new-interval",
      name: "Insert New Interval",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "rotate-matrix": {
      id: "rotate-matrix",
      name: "Rotate Matrix",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "number-of-one-bits": {
      id: "number-of-one-bits",
      name: "Number of One Bits",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "products-of-array-discluding-self": {
      id: "products-of-array-discluding-self",
      name: "Products of Array Discluding Self",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "longest-consecutive-sequence": {
      id: "longest-consecutive-sequence",
      name: "Longest Consecutive Sequence",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "three-integer-sum": {
      id: "three-integer-sum",
      name: "Three Integer Sum",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "max-water-container": {
      id: "max-water-container",
      name: "Max Water Container",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "longest-substring-without-duplicates": {
      id: "longest-substring-without-duplicates",
      name: "Longest Substring Without Duplicates",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "longest-repeating-substring-with-replacement": {
      id: "longest-repeating-substring-with-replacement",
      name: "Longest Repeating Substring With Replacement",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "minimum-window-with-characters": {
      id: "minimum-window-with-characters",
      name: "Minimum Window With Characters",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "find-target-in-rotated-sorted-array": {
      id: "find-target-in-rotated-sorted-array",
      name: "Find Target in Rotated Sorted Array",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "merge-two-sorted-linked-lists": {
      id: "merge-two-sorted-linked-lists",
      name: "Merge Two Sorted Linked Lists",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "reorder-linked-list": {
      id: "reorder-linked-list",
      name: "Reorder Linked List",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "remove-node-from-end-of-linked-list": {
      id: "remove-node-from-end-of-linked-list",
      name: "Remove Node From End of Linked List",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "linked-list-cycle-detection": {
      id: "linked-list-cycle-detection",
      name: "Linked List Cycle Detection",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "merge-k-sorted-linked-lists": {
      id: "merge-k-sorted-linked-lists",
      name: "Merge K Sorted Linked Lists",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "depth-of-binary-tree": {
      id: "depth-of-binary-tree",
      name: "Depth of Binary Tree",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "same-binary-tree": {
      id: "same-binary-tree",
      name: "Same Binary Tree",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "subtree-of-a-binary-tree": {
      id: "subtree-of-a-binary-tree",
      name: "Subtree of a Binary Tree",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "design-word-search-data-structure": {
      id: "design-word-search-data-structure",
      name: "Design Word Search Data Structure",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "search-for-word": {
      id: "search-for-word",
      name: "Search for Word",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "search-for-word-ii": {
      id: "search-for-word-ii",
      name: "Search for Word II",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "clone-graph": {
      id: "clone-graph",
      name: "Clone Graph",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "pacific-atlantic-water-flow": {
      id: "pacific-atlantic-water-flow",
      name: "Pacific Atlantic Water Flow",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "course-schedule": {
      id: "course-schedule",
      name: "Course Schedule",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "house-robber": {
      id: "house-robber",
      name: "House Robber",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "house-robber-ii": {
      id: "house-robber-ii",
      name: "House Robber II",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "longest-palindromic-substring": {
      id: "longest-palindromic-substring",
      name: "Longest Palindromic Substring",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "palindromic-substrings": {
      id: "palindromic-substrings",
      name: "Palindromic Substrings",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "decode-ways": {
      id: "decode-ways",
      name: "Decode Ways",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "coin-change": {
      id: "coin-change",
      name: "Coin Change",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "maximum-product-subarray": {
      id: "maximum-product-subarray",
      name: "Maximum Product Subarray",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "word-break": {
      id: "word-break",
      name: "Word Break",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "longest-increasing-subsequence": {
      id: "longest-increasing-subsequence",
      name: "Longest Increasing Subsequence",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "longest-common-subsequence": {
      id: "longest-common-subsequence",
      name: "Longest Common Subsequence",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "jump-game": {
      id: "jump-game",
      name: "Jump Game",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "merge-intervals": {
      id: "merge-intervals",
      name: "Merge Intervals",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "non-overlapping-intervals": {
      id: "non-overlapping-intervals",
      name: "Non-overlapping Intervals",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "spiral-matrix": {
      id: "spiral-matrix",
      name: "Spiral Matrix",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "set-zeroes-in-matrix": {
      id: "set-zeroes-in-matrix",
      name: "Set Zeroes in Matrix",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "counting-bits": {
      id: "counting-bits",
      name: "Counting Bits",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "reverse-bits": {
      id: "reverse-bits",
      name: "Reverse Bits",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "missing-number": {
      id: "missing-number",
      name: "Missing Number",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "sum-of-two-integers": {
      id: "sum-of-two-integers",
      name: "Sum of Two Integers",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "top-k-elements-in-list": {
      id: "top-k-elements-in-list",
      name: "Top K Elements in List",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "anagram-groups": {
      id: "anagram-groups",
      name: "Anagram Groups",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "lowest-common-ancestor-in-binary-search-tree": {
      id: "lowest-common-ancestor-in-binary-search-tree",
      name: "Lowest Common Ancestor in Binary Search Tree",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "level-order-traversal-of-binary-tree": {
      id: "level-order-traversal-of-binary-tree",
      name: "Level Order Traversal of Binary Tree",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "valid-binary-search-tree": {
      id: "valid-binary-search-tree",
      name: "Valid Binary Search Tree",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "kth-smallest-integer-in-bst": {
      id: "kth-smallest-integer-in-bst",
      name: "Kth Smallest Integer in BST",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "binary-tree-from-preorder-and-inorder-traversal": {
      id: "binary-tree-from-preorder-and-inorder-traversal",
      name: "Binary Tree from Preorder and Inorder Traversal",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "binary-tree-maximum-path-sum": {
      id: "binary-tree-maximum-path-sum",
      name: "Binary Tree Maximum Path Sum",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "serialize-and-deserialize-binary-tree": {
      id: "serialize-and-deserialize-binary-tree",
      name: "Serialize and Deserialize Binary Tree",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "valid-sudoku": {
      id: "valid-sudoku",
      name: "Valid Sudoku",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "two-integer-sum-ii": {
      id: "two-integer-sum-ii",
      name: "Two Integer Sum II",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "trapping-rain-water": {
      id: "trapping-rain-water",
      name: "Trapping Rain Water",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "permutation-string": {
      id: "permutation-string",
      name: "Permutation String",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "sliding-window-maximum": {
      id: "sliding-window-maximum",
      name: "Sliding Window Maximum",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "minimum-stack": {
      id: "minimum-stack",
      name: "Minimum Stack",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "evaluate-reverse-polish-notation": {
      id: "evaluate-reverse-polish-notation",
      name: "Evaluate Reverse Polish Notation",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "generate-parentheses": {
      id: "generate-parentheses",
      name: "Generate Parentheses",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "daily-temperatures": {
      id: "daily-temperatures",
      name: "Daily Temperatures",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "car-fleet": {
      id: "car-fleet",
      name: "Car Fleet",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "largest-rectangle-in-histogram": {
      id: "largest-rectangle-in-histogram",
      name: "Largest Rectangle In Histogram",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "binary-search": {
      id: "binary-search",
      name: "Binary Search",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "search-2d-matrix": {
      id: "search-2d-matrix",
      name: "Search 2D Matrix",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "eating-bananas": {
      id: "eating-bananas",
      name: "Eating Bananas",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "time-based-key-value-store": {
      id: "time-based-key-value-store",
      name: "Time Based Key-Value Store",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "median-of-two-sorted-arrays": {
      id: "median-of-two-sorted-arrays",
      name: "Median of Two Sorted Arrays",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "copy-linked-list-with-random-pointer": {
      id: "copy-linked-list-with-random-pointer",
      name: "Copy Linked List with Random Pointer",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "add-two-numbers": {
      id: "add-two-numbers",
      name: "Add Two Numbers",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "find-duplicate-integer": {
      id: "find-duplicate-integer",
      name: "Find Duplicate Integer",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "lru-cache": {
      id: "lru-cache",
      name: "LRU Cache",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "reverse-nodes-in-k-group": {
      id: "reverse-nodes-in-k-group",
      name: "Reverse Nodes in K-Group",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "binary-tree-diameter": {
      id: "binary-tree-diameter",
      name: "Binary Tree Diameter",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "balanced-binary-tree": {
      id: "balanced-binary-tree",
      name: "Balanced Binary Tree",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "binary-tree-right-side-view": {
      id: "binary-tree-right-side-view",
      name: "Binary Tree Right Side View",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "count-good-nodes-in-binary-tree": {
      id: "count-good-nodes-in-binary-tree",
      name: "Count Good Nodes in Binary Tree",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "kth-largest-integer-in-a-stream": {
      id: "kth-largest-integer-in-a-stream",
      name: "Kth Largest Integer in a Stream",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "last-stone-weight": {
      id: "last-stone-weight",
      name: "Last Stone Weight",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "k-closest-points-to-origin": {
      id: "k-closest-points-to-origin",
      name: "K Closest Points to Origin",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "kth-largest-element-in-an-array": {
      id: "kth-largest-element-in-an-array",
      name: "Kth Largest Element in an Array",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "task-scheduling": {
      id: "task-scheduling",
      name: "Task Scheduling",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "design-twitter-feed": {
      id: "design-twitter-feed",
      name: "Design Twitter Feed",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    subsets: {
      id: "subsets",
      name: "Subsets",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    permutations: {
      id: "permutations",
      name: "Permutations",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "subsets-ii": {
      id: "subsets-ii",
      name: "Subsets II",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "combination-target-sum-ii": {
      id: "combination-target-sum-ii",
      name: "Combination Target Sum II",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "palindrome-partitioning": {
      id: "palindrome-partitioning",
      name: "Palindrome Partitioning",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "combinations-of-a-phone-number": {
      id: "combinations-of-a-phone-number",
      name: "Combinations of a Phone Number",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "n-queens": {
      id: "n-queens",
      name: "N-Queens",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "max-area-of-island": {
      id: "max-area-of-island",
      name: "Max Area of Island",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "surrounded-regions": {
      id: "surrounded-regions",
      name: "Surrounded Regions",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "rotting-fruit": {
      id: "rotting-fruit",
      name: "Rotting Fruit",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "course-schedule-ii": {
      id: "course-schedule-ii",
      name: "Course Schedule II",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "redundant-connection": {
      id: "redundant-connection",
      name: "Redundant Connection",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "word-ladder": {
      id: "word-ladder",
      name: "Word Ladder",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "reconstruct-flight-path": {
      id: "reconstruct-flight-path",
      name: "Reconstruct Flight Path",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "min-cost-to-connect-points": {
      id: "min-cost-to-connect-points",
      name: "Min Cost to Connect Points",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "network-delay-time": {
      id: "network-delay-time",
      name: "Network Delay Time",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "swim-in-rising-water": {
      id: "swim-in-rising-water",
      name: "Swim in Rising Water",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "cheapest-flight-path": {
      id: "cheapest-flight-path",
      name: "Cheapest Flight Path",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "min-cost-climbing-stairs": {
      id: "min-cost-climbing-stairs",
      name: "Min Cost Climbing Stairs",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "partition-equal-subset-sum": {
      id: "partition-equal-subset-sum",
      name: "Partition Equal Subset Sum",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "buy-and-sell-crypto-with-cooldown": {
      id: "buy-and-sell-crypto-with-cooldown",
      name: "Buy and Sell Crypto with Cooldown",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "coin-change-ii": {
      id: "coin-change-ii",
      name: "Coin Change II",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "target-sum": {
      id: "target-sum",
      name: "Target Sum",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "interleaving-string": {
      id: "interleaving-string",
      name: "Interleaving String",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "longest-increasing-path-in-matrix": {
      id: "longest-increasing-path-in-matrix",
      name: "Longest Increasing Path in Matrix",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "count-subsequences": {
      id: "count-subsequences",
      name: "Count Subsequences",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "edit-distance": {
      id: "edit-distance",
      name: "Edit Distance",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "burst-balloons": {
      id: "burst-balloons",
      name: "Burst Balloons",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "regular-expression-matching": {
      id: "regular-expression-matching",
      name: "Regular Expression Matching",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "jump-game-ii": {
      id: "jump-game-ii",
      name: "Jump Game II",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "gas-station": {
      id: "gas-station",
      name: "Gas Station",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "hand-of-straights": {
      id: "hand-of-straights",
      name: "Hand of Straights",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "merge-triplets-to-form-target": {
      id: "merge-triplets-to-form-target",
      name: "Merge Triplets to Form Target",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "partition-labels": {
      id: "partition-labels",
      name: "Partition Labels",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "valid-parenthesis-string": {
      id: "valid-parenthesis-string",
      name: "Valid Parenthesis String",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "minimum-interval-including-query": {
      id: "minimum-interval-including-query",
      name: "Minimum Interval to Include Each Query",
      difficulty: "Hard",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "non-cyclical-number": {
      id: "non-cyclical-number",
      name: "Non-Cyclical Number",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "plus-one": {
      id: "plus-one",
      name: "Plus One",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "pow-x-n": {
      id: "pow-x-n",
      name: "Pow(x, n)",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "multiply-strings": {
      id: "multiply-strings",
      name: "Multiply Strings",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "count-squares": {
      id: "count-squares",
      name: "Count Squares",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "single-number": {
      id: "single-number",
      name: "Single Number",
      difficulty: "Easy",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "reverse-integer": {
      id: "reverse-integer",
      name: "Reverse Integer",
      difficulty: "Medium",
      free: true,
      tag: "NeetCode150",
      unreleased: true,
    },
    "python-hello-world": {
      id: "python-hello-world",
      name: "Hello, World",
      difficulty: "",
      free: true,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-what-is-python": {
      id: "python-what-is-python",
      name: "What is Python?",
      difficulty: "",
      free: true,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-execution-order": {
      id: "python-execution-order",
      name: "Execution Order",
      difficulty: "",
      free: true,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-printing-text": {
      id: "python-printing-text",
      name: "Printing Text",
      difficulty: "",
      free: true,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-code-errors": {
      id: "python-code-errors",
      name: "Code Errors",
      difficulty: "",
      free: true,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-comments": {
      id: "python-comments",
      name: "Comments",
      difficulty: "",
      free: true,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-variable-declaration": {
      id: "python-variable-declaration",
      name: "Variable Declaration",
      difficulty: "",
      free: true,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-variable-naming": {
      id: "python-variable-naming",
      name: "Variable Naming",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-naming-conventions": {
      id: "python-naming-conventions",
      name: "Naming Conventions",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-reassigning-variables": {
      id: "python-reassigning-variables",
      name: "Reassigning Variables",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-multiple-assignment": {
      id: "python-multiple-assignment",
      name: "Multiple Assignments",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-variable-types": {
      id: "python-variable-types",
      name: "Variable Types",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-dynamic-typing": {
      id: "python-dynamic-typing",
      name: "Dynamic Typing",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-type-casting": {
      id: "python-type-casting",
      name: "Type Casting",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-type-errors": {
      id: "python-type-errors",
      name: "Type Errors",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-empty-variable": {
      id: "python-empty-variable",
      name: "Empty Variable",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-arithmetic-operators": {
      id: "python-arithmetic-operators",
      name: "Arithmetic Operators",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-more-operators": {
      id: "python-more-operators",
      name: "More Operators",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-shorthand-operators": {
      id: "python-shorthand-operators",
      name: "Shorthand Operators",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-boolean-or": {
      id: "python-boolean-or",
      name: "Boolean OR",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-boolean-and": {
      id: "python-boolean-and",
      name: "Boolean AND",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-boolean-negation": {
      id: "python-boolean-negation",
      name: "Boolean Negation",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-introduction-to-functions": {
      id: "python-introduction-to-functions",
      name: "Introduction to Functions",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-function-declaration": {
      id: "python-function-declaration",
      name: "Function Declaration",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-parameters": {
      id: "python-parameters",
      name: "Parameters",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-multiple-parameters": {
      id: "python-multiple-parameters",
      name: "Multiple Parameters",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-return-statement": {
      id: "python-return-statement",
      name: "Return Statement",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-type-hints": {
      id: "python-type-hints",
      name: "Type Hints",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-scope": {
      id: "python-scope",
      name: "Scope",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-global-vs-local": {
      id: "python-global-vs-local",
      name: "Global vs Local Scope",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-default-arguments": {
      id: "python-default-arguments",
      name: "Default Arguments",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-comparison-operators": {
      id: "python-comparison-operators",
      name: "Comparison Operators",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-if": {
      id: "python-if",
      name: "If Statements",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-if-scope": {
      id: "python-if-scope",
      name: "If Statement Scope",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-if-else": {
      id: "python-if-else",
      name: "If-Else Statements",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-elif": {
      id: "python-elif",
      name: "Else-If Statements",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-logic-condition": {
      id: "python-logic-condition",
      name: "Logic Condition",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-truthy-and-falsy": {
      id: "python-truthy-and-falsy",
      name: "Truthy and Falsy",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-while-loops": {
      id: "python-while-loops",
      name: "While Loops",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-while-loops-counting": {
      id: "python-while-loops-counting",
      name: "While Loops Counting",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-while-loops-multiples": {
      id: "python-while-loops-multiples",
      name: "While Loops Multiples",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-for-loops": {
      id: "python-for-loops",
      name: "For Loops",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-for-loops-start": {
      id: "python-for-loops-start",
      name: "For Loops Start",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-for-loops-step": {
      id: "python-for-loops-step",
      name: "For Loops Step",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-for-loops-reverse": {
      id: "python-for-loops-reverse",
      name: "For Loops Reverse",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-nested-loops": {
      id: "python-nested-loops",
      name: "Nested Loops",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-control-flow": {
      id: "python-control-flow",
      name: "Control Flow",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-length-function": {
      id: "python-length-function",
      name: "Length Function",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-string-indexing": {
      id: "python-string-indexing",
      name: "String Indexing",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-string-looping": {
      id: "python-string-looping",
      name: "String Looping",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-string-looping-shorthand": {
      id: "python-string-looping-shorthand",
      name: "String Looping Shorthand",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-string-concatenation": {
      id: "python-string-concatenation",
      name: "String Concatenation",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-string-slicing-part-1": {
      id: "python-string-slicing-part-1",
      name: "String Slicing Part 1",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-string-slicing-part-2": {
      id: "python-string-slicing-part-2",
      name: "String Slicing Part 2",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-reversing-a-string": {
      id: "python-reversing-a-string",
      name: "Reversing a String",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-strings-are-immutable": {
      id: "python-strings-are-immutable",
      name: "Strings are Immutable",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-string-formatting": {
      id: "python-string-formatting",
      name: "String Formatting",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-intro-to-lists": {
      id: "python-intro-to-lists",
      name: "Intro to Lists",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-list-operations": {
      id: "python-list-operations",
      name: "List Operations",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-list-looping": {
      id: "python-list-looping",
      name: "List Looping",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-list-functions": {
      id: "python-list-functions",
      name: "List Functions",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-list-append": {
      id: "python-list-append",
      name: "List Append",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-list-pop": {
      id: "python-list-pop",
      name: "List Pop",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-list-find": {
      id: "python-list-find",
      name: "List Find",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-list-slicing": {
      id: "python-list-slicing",
      name: "List Slicing",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-tuples": {
      id: "python-tuples",
      name: "Tuples",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-intro-to-sets": {
      id: "python-intro-to-sets",
      name: "Intro to Sets",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-set-operations": {
      id: "python-set-operations",
      name: "Set Operations",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-set-practice": {
      id: "python-set-practice",
      name: "Set Practice",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-intro-to-dictionaries": {
      id: "python-intro-to-dictionaries",
      name: "Intro to Dictionaries",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-dict-operations": {
      id: "python-dict-operations",
      name: "Dict Operations",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-dict-looping": {
      id: "python-dict-looping",
      name: "Dict Looping",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-dict-practice": {
      id: "python-dict-practice",
      name: "Dict Practice",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-dict-remove": {
      id: "python-dict-remove",
      name: "Dict Remove",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-dict-values": {
      id: "python-dict-values",
      name: "Dict Values",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-read-input": {
      id: "python-read-input",
      name: "Reading Input",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-type-conversion-input": {
      id: "python-type-conversion-input",
      name: "Type Conversion with Input",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-parse-input": {
      id: "python-parse-input",
      name: "Parse Input",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-read-input-practice": {
      id: "python-read-input-practice",
      name: "Reading Input Practice",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-try-except": {
      id: "python-try-except",
      name: "Try Except",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-error-catching": {
      id: "python-error-catching",
      name: "Error Catching",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-multiple-except-blocks": {
      id: "python-multiple-except-blocks",
      name: "Multiple Except Blocks",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-for-beginners",
    },
    "python-sort-ascending": {
      id: "python-sort-ascending",
      name: "Sort Ascending",
      difficulty: "",
      free: true,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-sort-descending": {
      id: "python-sort-descending",
      name: "Sort Descending",
      difficulty: "",
      free: true,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-sort-custom": {
      id: "python-sort-custom",
      name: "Sort Custom",
      difficulty: "",
      free: true,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-sort-lambda": {
      id: "python-sort-lambda",
      name: "Sort Lambda",
      difficulty: "",
      free: true,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-sorted-copy": {
      id: "python-sorted-copy",
      name: "Sorted Copy",
      difficulty: "",
      free: true,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-unpacking": {
      id: "python-unpacking",
      name: "Unpacking",
      difficulty: "",
      free: true,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-loop-unpacking": {
      id: "python-loop-unpacking",
      name: "Loop Unpacking",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-enumerate": {
      id: "python-enumerate",
      name: "Enumerate",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-zip": {
      id: "python-zip",
      name: "Zip",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-inequality": {
      id: "python-inequality",
      name: "Inequality",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-min-max-shortcut": {
      id: "python-min-max-shortcut",
      name: "Min Max Shortcut",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-resizable-list-part-1": {
      id: "python-resizable-list-part-1",
      name: "Resizable List Part 1",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-resizable-list-part-2": {
      id: "python-resizable-list-part-2",
      name: "Resizable List Part 2",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-list-concat": {
      id: "python-list-concat",
      name: "List Concat",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-list-initialization": {
      id: "python-list-initialization",
      name: "List Initialization",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-list-clone": {
      id: "python-list-clone",
      name: "List Clone",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-list-comprehension": {
      id: "python-list-comprehension",
      name: "List Comprehension",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-stack-push-pop": {
      id: "python-stack-push-pop",
      name: "Stack Push and Pop",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-queue-enqueue-dequeue": {
      id: "python-queue-enqueue-dequeue",
      name: "Queue Enqueue and Dequeue",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-double-ended-queue": {
      id: "python-double-ended-queue",
      name: "Double Ended Queue",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-multi-dimensional-list": {
      id: "python-multi-dimensional-list",
      name: "Multi-Dimensional List",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-2d-grid": {
      id: "python-2d-grid",
      name: "2D Grid",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-nested-list-comprehension": {
      id: "python-nested-list-comprehension",
      name: "Nested List Comprehension",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-hash-map-basics": {
      id: "python-hash-map-basics",
      name: "Hash Map Basics",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-default-dict": {
      id: "python-default-dict",
      name: "Default Dict",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-counter": {
      id: "python-counter",
      name: "Counter",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-dict-comprehension": {
      id: "python-dict-comprehension",
      name: "Dict Comprehension",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-dict-items": {
      id: "python-dict-items",
      name: "Dict Items",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-hash-set-basics": {
      id: "python-hash-set-basics",
      name: "Hash Set Basics",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-set-comprehension": {
      id: "python-set-comprehension",
      name: "Set Comprehension",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-tuple-keys": {
      id: "python-tuple-keys",
      name: "Tuple Keys",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-heap-push": {
      id: "python-heap-push",
      name: "Heap Push",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-heap-pop": {
      id: "python-heap-pop",
      name: "Heap Pop",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-heapify": {
      id: "python-heapify",
      name: "Heapify",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-max-heap": {
      id: "python-max-heap",
      name: "Max Heap",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-custom-heap": {
      id: "python-custom-heap",
      name: "Custom Heap",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-heap-n-smallest": {
      id: "python-heap-n-smallest",
      name: "Heap N Smallest",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-heap-n-largest": {
      id: "python-heap-n-largest",
      name: "Heap N Largest",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-sorted-dict-basics": {
      id: "python-sorted-dict-basics",
      name: "Sorted Dict Basics",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "python-sorted-set-basics": {
      id: "python-sorted-set-basics",
      name: "Sorted Set Basics",
      difficulty: "",
      free: null,
      tag: "Python For Beginners",
      unreleased: null,
      course: "python-coding-interviews",
    },
    "sql-create-table": {
      id: "sql-create-table",
      name: "Create Table",
      difficulty: "",
      free: true,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-capitalization": {
      id: "sql-capitalization",
      name: "Capitalization",
      difficulty: "",
      free: true,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-table-rows": {
      id: "sql-table-rows",
      name: "Table Rows",
      difficulty: "",
      free: true,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-default-values": {
      id: "sql-default-values",
      name: "Default Values",
      difficulty: "",
      free: true,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-alter-table": {
      id: "sql-alter-table",
      name: "Alter Table",
      difficulty: "",
      free: true,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-drop-table": {
      id: "sql-drop-table",
      name: "Drop Table",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-not-null-constraint": {
      id: "sql-not-null-constraint",
      name: "Not Null Constraint",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-unique-constraint": {
      id: "sql-unique-constraint",
      name: "Unique Constraint",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-primary-key": {
      id: "sql-primary-key",
      name: "Primary Key",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-foreign-key": {
      id: "sql-foreign-key",
      name: "Foreign Key",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-composite-primary-key": {
      id: "sql-composite-primary-key",
      name: "Composite Primary Key",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-check-constraint": {
      id: "sql-check-constraint",
      name: "Check Constraint",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-booleans": {
      id: "sql-booleans",
      name: "Booleans",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-numbers": {
      id: "sql-numbers",
      name: "Numbers",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-strings": {
      id: "sql-strings",
      name: "Strings",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-dates": {
      id: "sql-dates",
      name: "Dates",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-arrays": {
      id: "sql-arrays",
      name: "Arrays",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-enum": {
      id: "sql-enum",
      name: "Enum",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-auto-increment": {
      id: "sql-auto-increment",
      name: "Auto Increment",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-uuid": {
      id: "sql-uuid",
      name: "UUID",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-insert-basics": {
      id: "sql-insert-basics",
      name: "Insert Basics",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-insert-default-values": {
      id: "sql-insert-default-values",
      name: "Insert Default Values",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-insert-array": {
      id: "sql-insert-array",
      name: "Insert Arrays",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-insert-constraints": {
      id: "sql-insert-constraints",
      name: "Insert Constraints",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-select-everything": {
      id: "sql-select-everything",
      name: "Select Everything",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-select-columns": {
      id: "sql-select-columns",
      name: "Select Columns",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-select-where": {
      id: "sql-select-where",
      name: "Select Where",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-select-where-not": {
      id: "sql-select-where-not",
      name: "Select Where Not",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-select-where-comparison": {
      id: "sql-select-where-comparison",
      name: "Select Where Comparison",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-select-null": {
      id: "sql-select-null",
      name: "Select Null",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-select-distinct": {
      id: "sql-select-distinct",
      name: "Select Distinct",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-select-like": {
      id: "sql-select-like",
      name: "Select Like",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-select-in": {
      id: "sql-select-in",
      name: "Select In",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-select-between": {
      id: "sql-select-between",
      name: "Select Between",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-select-logical-operators": {
      id: "sql-select-logical-operators",
      name: "Select Logical Operators",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-select-order-by": {
      id: "sql-select-order-by",
      name: "Select Order By",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-select-limit": {
      id: "sql-select-limit",
      name: "Select Limit",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-update-all": {
      id: "sql-update-all",
      name: "Update All",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-update-where": {
      id: "sql-update-where",
      name: "Update Where",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-update-returning": {
      id: "sql-update-returning",
      name: "Update Returning",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-update-constraints": {
      id: "sql-update-constraints",
      name: "Update Constraints",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-delete-all": {
      id: "sql-delete-all",
      name: "Delete All",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-delete-where": {
      id: "sql-delete-where",
      name: "Delete Where",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-delete-returning": {
      id: "sql-delete-returning",
      name: "Delete Returning",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-delete-constraints": {
      id: "sql-delete-constraints",
      name: "Delete Constraints",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-delete-truncate": {
      id: "sql-delete-truncate",
      name: "Delete Truncate",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-aggregation-sum": {
      id: "sql-aggregation-sum",
      name: "Aggregation Sum",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-aggregation-avg": {
      id: "sql-aggregation-avg",
      name: "Aggregation Avg",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-aggregation-count": {
      id: "sql-aggregation-count",
      name: "Aggregation Count",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-aggregation-min-max": {
      id: "sql-aggregation-min-max",
      name: "Aggregation Min Max",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-aggregation-group-by": {
      id: "sql-aggregation-group-by",
      name: "Aggregation Group By",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-aggregation-group-by-multiple": {
      id: "sql-aggregation-group-by-multiple",
      name: "Aggregation Group By Multiple",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-aggregation-group-by-distinct": {
      id: "sql-aggregation-group-by-distinct",
      name: "Aggregation Group By Distinct",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-aggregation-having": {
      id: "sql-aggregation-having",
      name: "Aggregation Having",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-aggregation-execution-order": {
      id: "sql-aggregation-execution-order",
      name: "Aggregation Execution Order",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-join-basics": {
      id: "sql-join-basics",
      name: "Join Basics",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-inner-join": {
      id: "sql-inner-join",
      name: "Inner Join",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-table-alias": {
      id: "sql-table-alias",
      name: "Table Alias",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-left-join": {
      id: "sql-left-join",
      name: "Left Join",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-right-join": {
      id: "sql-right-join",
      name: "Right Join",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-full-join": {
      id: "sql-full-join",
      name: "Full Join",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-multi-join": {
      id: "sql-multi-join",
      name: "Multi Join",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-normalized-tables": {
      id: "sql-normalized-tables",
      name: "Normalized Tables",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-one-to-one": {
      id: "sql-one-to-one",
      name: "One-to-One Relationships",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-one-to-many": {
      id: "sql-one-to-many",
      name: "One to Many",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-many-to-many": {
      id: "sql-many-to-many",
      name: "Many-to-Many Relationships",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-subqueries-where": {
      id: "sql-subqueries-where",
      name: "Subqueries in WHERE clause",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-subqueries-from": {
      id: "sql-subqueries-from",
      name: "Subqueries in FROM clause",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-exists": {
      id: "sql-exists",
      name: "EXISTS",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-any-all": {
      id: "sql-any-all",
      name: "ANY and ALL",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-common-table-expressions": {
      id: "sql-common-table-expressions",
      name: "Common Table Expressions",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-case-expressions": {
      id: "sql-case-expressions",
      name: "CASE Expressions",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-indexes": {
      id: "sql-indexes",
      name: "Indexes",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-index-types": {
      id: "sql-index-types",
      name: "Index Types",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "sql-read-indexes": {
      id: "sql-read-indexes",
      name: "Read Indexes",
      difficulty: "",
      free: null,
      tag: "SQL",
      unreleased: null,
      course: "sql-for-beginners",
    },
    "gradient-descent": {
      id: "gradient-descent",
      name: "Gradient Descent",
      difficulty: "Easy",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
    },
    "linear-regression-forward": {
      id: "linear-regression-forward",
      name: "Linear Regression (Forward)",
      difficulty: "Easy",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
    },
    "linear-regression-training": {
      id: "linear-regression-training",
      name: "Linear Regression (Training)",
      difficulty: "Medium",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
    },
    "neural-networks": {
      id: "neural-networks",
      name: "Neural Networks",
      difficulty: "Easy",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
      quiz: true,
    },
    "basics-of-pytorch": {
      id: "basics-of-pytorch",
      name: "Pytorch Basics",
      difficulty: "Easy",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
    },
    "handwritten-digit-classifier": {
      id: "handwritten-digit-classifier",
      name: "Digit Classifier",
      difficulty: "Medium",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
    },
    "pytorch-training": {
      id: "pytorch-training",
      name: "PyTorch Training",
      difficulty: "Easy",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
      quiz: true,
    },
    "nlp-intro": {
      id: "nlp-intro",
      name: "Intro to Natural Language Processing",
      difficulty: "Medium",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
    },
    "sentiment-analysis": {
      id: "sentiment-analysis",
      name: "Sentiment Analysis",
      difficulty: "Medium",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
    },
    "gpt-dataset": {
      id: "gpt-dataset",
      name: "GPT Dataset",
      difficulty: "Medium",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
    },
    "self-attention": {
      id: "self-attention",
      name: "Self Attention",
      difficulty: "Hard",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
    },
    "multi-headed-self-attention": {
      id: "multi-headed-self-attention",
      name: "Multi Headed Self Attention",
      difficulty: "Medium",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
    },
    "transformer-block": {
      id: "transformer-block",
      name: "Transformer Block",
      difficulty: "Medium",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
    },
    "code-gpt": {
      id: "code-gpt",
      name: "Code GPT",
      difficulty: "Medium",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
    },
    "make-gpt-talk-back": {
      id: "make-gpt-talk-back",
      name: "Make GPT Talk Back",
      difficulty: "Hard",
      free: true,
      tag: "Machine Learning",
      unreleased: null,
    },
  },
};
